problem: CartPole-v1
has_continuous_space: true
has_continuous_actions: false
n_episodes: 2500
print_freq: 10
random_seed: 543 # 0 means no seed

# agent
gamma: 0.99
n_steps: 100
# net_arch: mlp_medium # can be mlp_small, mlp_medium or conv
learning_rate: 0.0009
entropy_reg: 0.01
